---
- name: Dev preparation
  hosts: localhost
  connection: local
  vars:
    username: antonov
    user_shell: /bin/bash
    home: "/home/{{ username }}"
  roles:
    - vmware_specific_setup
    - role: environment_setup
      vars:
        additional_packages:
          - scala
    - role: intelij_idea_setup
      vars:
        additional_plugins:
          - { id: "org.intellij.scala", folder_to_check: "Scala" }
    - role: git_setup
      vars:
        additional_repositories:
          - Learning
          - crud-wishlist-scala-sqlite
    - oracle_sql_developer_setup
