---

- name: dev preparation
  hosts: localhost
  connection: local
  tasks:
  - name: Mount VM Ware shared folder
    when: ansible_facts['virtualization_type'] == 'VMware'
    mount:
      path: /mnt/hgfs
      src: vmhgfs-fuse
      fstype: fuse
      opts: defaults,allow_other
      state: present

  - name: install packages
    package:
      name: 
        - vim
        - mc
        - git
        - openjdk-17-jdk-headless
        - scala
        - docker.io
        - docker-compose
      state: present

  - name: Install Intelij Idea, Visual Studio Code using snap repo
    snap:
      name: 
        - intellij-idea-community
        - code
      classic: true

  - name: Read intelij idea info file
    shell: cat /snap/intellij-idea-community/current/product-info.json
    register: intelij_info_output
  - name: save the intelij_info_output as json object
    set_fact:
      intelij_info_json: "{{ intelij_info_output.stdout | from_json }}"
  - name: read intelij folder name for plugins from intelij_info_json
    set_fact:
      intelij_directory_name_for_plugins: "{{ intelij_info_json | json_query('dataDirectoryName') }}"

  - name: install intelij idea plugins
    become_user: antonov
    become: true
    shell: '[ -d /home/antonov/.local/share/JetBrains/{{ intelij_directory_name_for_plugins }}/plugins/{{ item.folder_to_check }} ] || [ -f /home/antonov/.cache/JetBrains/{{ intelij_directory_name_for_plugins }}/plugins/{{ item.folder_to_check }}.zip ] || /snap/intellij-idea-community/current/bin/idea.sh installPlugins {{ item.id }} || echo true'
    args:
      executable: /bin/bash
    loop:
      - { id: "org.intellij.scala", folder_to_check: "Scala" }   