---
- name: Dev preparation
  hosts: localhost
  connection: local
  vars:
    username: antonov
    user_shell: /bin/bash
    home: "/home/{{ username }}"
  roles:
    - vmware_specific_setup
    - environment_setup
    - intelij_idea_setup
    - git_setup
    - oracle_sql_developer_setup