---
- name: Dev preparation
  hosts: localhost
  connection: local
  vars:
    username: dmitrii
    user_shell: /bin/bash
    home: "/home/{{ username }}"
  roles:
    - vmware_specific_setup
    - role: environment_setup
      vars:
        additional_packages:
          - maven
          - gradle
    - intelij_idea_setup
    - role: git_setup
      vars:
        additional_repositories:
          - learning-aws-lambda
          - learning-aws-lambda-springboot
          - bridle
          - earthquake
    - oracle_sql_developer_setup
    - aws_soft_setup
